//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentTransaction
    {
        public long TransactionId { get; set; }
        public int CustomerId { get; set; }
        public int OrderId { get; set; }
        public long PaymentCrAmount { get; set; }
        public long PaymentDrAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentReceivedBy { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    }
}
