//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public long OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public long OrderProductId { get; set; }
        public System.DateTime OrderPurchaseDtm { get; set; }
        public int OrderQuantity { get; set; }
        public long OrderPrice { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime OrderDeilveredDate { get; set; }
        public int OrderDeilveredBy { get; set; }
        public Nullable<int> OrderCustomerId { get; set; }
        public int OrderPaymentMode { get; set; }
        public string OrderComments { get; set; }
        public Nullable<long> OrderAmount { get; set; }
        public Nullable<long> OrderTax { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverNumber { get; set; }
        public string JCBDriverNumber { get; set; }
        public string RoyaltyNumber { get; set; }
        public string OrderPriority { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    
        public virtual ProductSiteMapping ProductSiteMapping { get; set; }
    }
}
