//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderDetail
    {
        public long ProductOrderDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> UnitPrice { get; set; }
        public Nullable<long> Total { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
    }
}
